### ISSUE TITLE
Unable to compile on Ubuntu 15.04

### ISSUE THREAD

**Issue by hellocatfood** [mikeryan/ems-flasher#5]
I'm attempting to compile ems-flasher from commit d90fa3fe97 on Ubuntu 15.04. I have pkg-config 0.28-1ubuntu1 and libusb-1.0.0-dev 2:1.0.19-1.

When I run `make` I get the following error and the program fails to compile

````
cc -g -Wall -Werror -pedantic -std=c99 `pkg-config --cflags libusb-1.0` -c ems.c
In file included from ems.c:2:0:
/usr/local/include/err.h:8:1: error: unknown type name ‘namespace’
 namespace stasm
 ^
/usr/local/include/err.h:9:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 {
 ^
ems.c: In function ‘ems_write’:
ems.c:219:9: error: implicit declaration of function ‘err’ [-Werror=implicit-function-declaration]
         err(1, "malloc");
         ^
cc1: all warnings being treated as errors
Makefile:21: recipe for target 'ems.o' failed
make: *** [ems.o] Error 1
````

**Comment by mikeryan** [comment]
I'm having trouble reproducing this on a fresh install of Ubuntu 15.04. Can you please provide the output of ```cc --version```, ```which cc```, and ```echo $PATH```

**Comment by hellocatfood** [comment]
`cc --version` output:
````
cc (Ubuntu 4.9.2-10ubuntu13) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
````

`which cc` output:
````
/usr/bin/cc
````

`echo $PATH` output
````
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
````

**Comment by chastai** [comment]
The compilation failed because the wrong err.h was used on the hellocatfood's system: /usr/local/include/err.h -- which probably belongs to a C++ software (namespace stasm) -- takes precedence over  /usr/include/err.h.
You could reinstall properly the culprit software or possibly change #include <err.h> by #include "/usr/include/err.h".

Christophe.
