### ISSUE TITLE
Cannot compile on Ubuntu 22.04

### ISSUE THREAD

**Issue by hellocatfood** [mikeryan/ems-flasher#27]
I'm attempting to compile the ems-flasher on Ubuntu 22.04. Running `./config` outputs the following:

```
./config.sh 
CC=cc
CFLAGS=-g -Wall -Werror -pedantic -std=c99
BINDIR=/usr/local/bin
DATADIR=/usr/local/share/ems-flasher
MANDIR=/usr/local/share/man
UDEVRULESDIR=/lib/udev/rules.d
libusb-1.0 doesn't seem to use libpthread. Fine.
```

`make` still runs but fails:

```
make
cc -c -g -Wall -Werror -pedantic -std=c99 -I/usr/include/libusb-1.0 -o ems.o ems.c
cc -g -Wall -Werror -pedantic -std=c99   -c -o main.o main.c
cc -g -Wall -Werror -pedantic -std=c99   -c -o header.o header.c
cc -g -Wall -Werror -pedantic -std=c99   -c -o cmd.o cmd.c
cc -g -Wall -Werror -pedantic -std=c99   -c -o updates.o updates.c
cc -g -Wall -Werror -pedantic -std=c99   -c -o progress.o progress.c
cc -g -Wall -Werror -pedantic -std=c99   -c -o flash.o flash.c
cc -g -Wall -Werror -pedantic -std=c99   -c -o insert.o insert.c
cc -g -Wall -Werror -pedantic -std=c99   -c -o update.o update.c
./updateheader.sh -c -s  < menu.gb > menucs.gb
./updateheader.sh -c < menu.gb > menuc.gb
./updateheader.sh -s < menu.gb > menus.gb
cc  -g -Wall -Werror -pedantic -std=c99 -o ems-flasher-real ems.o main.o header.o cmd.o updates.o progress.o flash.o insert.o update.o  -lusb-1.0 
/usr/bin/ld: updates.o:/home/hellocatfood/Desktop/ems-flasher/flash.h:11: multiple definition of `flash_lastofs'; cmd.o:/home/hellocatfood/Desktop/ems-flasher/flash.h:11: first defined here
/usr/bin/ld: updates.o:/home/hellocatfood/Desktop/ems-flasher/flash.h:12: multiple definition of `flash_lasterrorstr'; cmd.o:/home/hellocatfood/Desktop/ems-flasher/flash.h:12: first defined here
/usr/bin/ld: progress.o:/home/hellocatfood/Desktop/ems-flasher/flash.h:11: multiple definition of `flash_lastofs'; cmd.o:/home/hellocatfood/Desktop/ems-flasher/flash.h:11: first defined here
/usr/bin/ld: progress.o:/home/hellocatfood/Desktop/ems-flasher/flash.h:12: multiple definition of `flash_lasterrorstr'; cmd.o:/home/hellocatfood/Desktop/ems-flasher/flash.h:12: first defined here
/usr/bin/ld: flash.o:/home/hellocatfood/Desktop/ems-flasher/flash.h:11: multiple definition of `flash_lastofs'; cmd.o:/home/hellocatfood/Desktop/ems-flasher/flash.h:11: first defined here
/usr/bin/ld: flash.o:/home/hellocatfood/Desktop/ems-flasher/flash.h:12: multiple definition of `flash_lasterrorstr'; cmd.o:/home/hellocatfood/Desktop/ems-flasher/flash.h:12: first defined here
/usr/bin/ld: insert.o:/home/hellocatfood/Desktop/ems-flasher/insert.h:7: multiple definition of `insert_pagesize'; cmd.o:/home/hellocatfood/Desktop/ems-flasher/insert.h:7: first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:37: ems-flasher-real] Error 1
```

**Comment by skipcloud** [comment]
Just stumbled across this as I ran into the same issue. Looks like it's more of a problem with `ld` than the code
https://bugzilla.redhat.com/show_bug.cgi?id=1869902

If you add `-fcommon` to the cflags in the makefile it'll compile :) second line should be this

```
CFLAGS = -g -Wall -Werror -pedantic -std=c99 -fcommon
```

**Comment by hellocatfood** [comment]
Thanks @skipcloud , that worked!
